services:
  api:
    build: .
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    depends_on:
      - pg_db
  pg_db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    env_file:
      - ./.env
